"""Initial migration.

Revision ID: 5b7e4348d602
Revises: 
Create Date: 2023-09-14 15:18:04.584850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7e4348d602'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('villains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('secret_lair', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herovillains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('villain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], name=op.f('fk_herovillains_hero_id_heroes')),
    sa.ForeignKeyConstraint(['villain_id'], ['villains.id'], name=op.f('fk_herovillains_villain_id_villains')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('herovillains')
    op.drop_table('villains')
    op.drop_table('heroes')
    # ### end Alembic commands ###
